### ISSUE TITLE
Support password detection/managers

### ISSUE THREAD

**Issue by alexruf** [mattDavo/Yippy#26]
Would be great to have support for password detection for those who are working with password managers like 1Password, LastPass etc.
I think there are multiple options to deal with this. Some clipboard managers allow specifying applications which should be excluded from clipboard management. Personally I was using the clipboard manager build into Keyboard Maestro for a long time, which had a pretty good way to deal with this. There was an option called "Detect (and conceal) possible passwords". What it basically did was, if it detected a possible password (not sure how they exactly distinguish passwords from normal text), it concealed the whole text except the first two letters or so. Liked that very much since it worked pretty well no matter from where you copy the password.
No matter how it's done, passwords should not be stored in plain text in the clipboard history.

**Comment by marcelismus** [comment]
+1

**Comment by Rediwed** [comment]
I have to more possible solutions:

1) Introduce a modifier key to the copy shortcut where it doesn't store the string in the manager. For instance: Cmd+C to copy and store in manager and Shift+Cmd+C to only copy in clipboard (not in manager)

2) Introduce a shortcut to set a temporary privacy-mode, where it will not store anything from the clipboard in the manager for the following 30 seconds or minute or so. Also introduce a toast notification or something to notify the user about the clipboard manager entering/exiting privacy mode. This solution would also solve the situation where a Password manager’s UI button to copy a password is used instead of a shortcut.

**Comment by karlhorky** [comment]
I think this has been fixed in version `2.5.0` already (original work done in `2.4.1` and `2.4.2`):

https://github.com/mattDavo/Yippy/issues/18

@alexruf can this be closed?

**Comment by Speed1** [comment]
Passwords copied directly from 1Password are not shown anymore in Yippy (great!!!), but when I copy them from the 1Password Chrome Extension they still get added to the Yippy history.
Maybe this could be solved somehow?

**Comment by beeb** [comment]
I think this doesn't work with 1Password 8. (bundle identifier `com.1password.1password`)

**Comment by karlhorky** [comment]
Thanks @beeb for the PR https://github.com/mattDavo/Yippy/pull/56 to add the 1Password 8 bundle identifier!
